runtime: nodejs16

# env_variables: 
#     APP_NAME: API GATEWAY
#     # AUTH_SERVICE_PORT: http://localhost:8001
#     AUTH_SERVICE_PORT: https://auth-service-p2p.as.r.appspot.com
#     LENDER_SERVICE_PORT: http://localhost:8002
#     BORROWER_SERVICE_PORT: http://localhost:8003
#     FUNDING_SERVICE_PORT: http://localhost:8004
#     PORT: 8000
#     ACCESS_TOKEN_PRIVATE_KEY: "**2%$23ndjaeadjFHC$$8839HyUJJuu@@$%jdi!jd"
#     SESSION_SECRET: 98&3jajdhYhda%dj@jidDcva3dD